import { V1_PRICE_PRESENTATION } from './capabilities'
import type { StoreCategoryId, StoreTemplate, TemplateSlug } from './types'
import { TEMPLATE_SLUGS } from './types'

export const STORE_CATEGORY_LABELS = {
  kuliner: 'Kuliner',
  retail: 'Retail',
  'jasa-profesional': 'Jasa Profesional',
  'klinik-wellness': 'Klinik & Wellness',
  edukasi: 'Edukasi',
  rental: 'Rental',
} as const satisfies Record<StoreCategoryId, string>

export const STORE_STATUS_LABELS = {
  preview: 'Preview tersedia',
  live: 'Live',
  'coming-soon': 'Segera hadir',
} as const

export const BUSINESS_TYPE_LABELS = {
  restaurant: 'Restoran',
  cafe: 'Kafe',
  bakery: 'Toko roti',
  'food-service': 'Bisnis makanan',
  'retail-brand': 'Brand retail',
  'fashion-brand': 'Brand fashion',
  'home-living': 'Home & living',
  'lifestyle-brand': 'Brand lifestyle',
  consultant: 'Konsultan',
  agency: 'Agensi',
  'professional-practice': 'Praktik profesional',
  'creative-studio': 'Studio kreatif',
  clinic: 'Klinik',
  practitioner: 'Praktisi',
  'wellness-practice': 'Wellness',
  'course-provider': 'Penyelenggara kursus',
  tutoring: 'Bimbingan belajar',
  'training-center': 'Pusat pelatihan',
  academy: 'Akademi',
  'car-rental': 'Rental mobil',
  'motorcycle-rental': 'Rental motor',
  'equipment-rental': 'Rental peralatan',
  'property-rental': 'Rental properti',
} as const

export const STORE_TEMPLATES_BY_SLUG = {
  'warm-commerce': {
    slug: 'warm-commerce',
    name: 'Warm Commerce',
    shortName: 'Warm',
    category: 'kuliner',
    businessTypes: ['restaurant', 'cafe', 'bakery', 'food-service'],
    capabilities: [
      'public.catalog',
      'public.item-detail',
      'public.price-display',
      'public.whatsapp-contact',
      'public.order-request',
      'public.location',
      'public.process',
    ],
    optionalCapabilities: [
      'ops.content-management',
      'ops.order-management',
      'ops.inquiry-follow-up',
      'ops.inventory',
      'ops.customer-records',
      'ops.internal-users',
      'ops.admin-dashboard',
      'account.customer-login',
      'account.order-tracking',
    ],
    shortDescription: 'Untuk bisnis makanan yang membutuhkan menu jelas, informasi harga, dan jalur permintaan order yang langsung.',
    positioning: 'Contoh tampilan berbasis menu yang membantu bisnis makanan mengubah kunjungan menjadi percakapan order yang jelas.',
    customerCan: [
      'public.catalog',
      'public.item-detail',
      'public.price-display',
      'public.whatsapp-contact',
      'public.order-request',
    ],
    includedFeatures: [
      'Menu dan katalog makanan',
      'Detail produk dan contoh harga',
      'Permintaan order langsung melalui WhatsApp',
      'Lokasi dan informasi kunjungan',
    ],
    optionalFeatures: [
      'Kelola katalog, order, stok, dan data pelanggan',
      'Halaman kerja untuk operasional tim',
      'Login pelanggan dan lacak order sesuai kebutuhan',
    ],
    previewStatus: 'preview',
    runtimeStatus: 'local',
    runtimeOwner: 'canonical-store',
    storeIndexVisibility: 'visible',
    detailRoute: '/store/template/warm-commerce',
    previewRoute: '/store/template/warm-commerce/preview',
    customizeRoute: '/store/customize/warm-commerce',
    pricePresentation: V1_PRICE_PRESENTATION,
    baseRecommendation: 'website',
    upgradeRecommendation: 'website-portal',
    featured: true,
    sortOrder: 1,
    runtimeKey: 'warm-commerce',
  },
  'modern-catalog': {
    slug: 'modern-catalog',
    name: 'Modern Catalog',
    shortName: 'Modern',
    category: 'retail',
    businessTypes: ['retail-brand', 'fashion-brand', 'home-living', 'lifestyle-brand'],
    capabilities: [
      'public.catalog',
      'public.item-detail',
      'public.search-filter',
      'public.price-display',
      'public.inquiry',
      'public.whatsapp-contact',
      'public.process',
    ],
    optionalCapabilities: [
      'ops.content-management',
      'ops.order-management',
      'ops.inventory',
      'ops.customer-records',
      'ops.internal-users',
      'ops.admin-dashboard',
      'account.customer-login',
      'account.order-tracking',
    ],
    shortDescription: 'Untuk koleksi pilihan yang perlu konteks sebelum orang bertanya.',
    positioning: 'Contoh tampilan berbasis produk untuk koleksi yang perlu dijelaskan sebelum percakapan dimulai.',
    customerCan: [
      'public.catalog',
      'public.item-detail',
      'public.search-filter',
      'public.price-display',
      'public.inquiry',
      'public.whatsapp-contact',
    ],
    includedFeatures: [
      'Katalog produk dan koleksi',
      'Pencarian dan filter pilihan',
      'Detail produk, varian, dan contoh harga',
      'Jalur pertanyaan lanjutan',
    ],
    optionalFeatures: [
      'Kelola katalog, order, stok, dan data pelanggan',
      'Halaman kerja untuk operasional tim',
      'Login pelanggan dan lacak order sesuai kebutuhan',
    ],
    previewStatus: 'preview',
    runtimeStatus: 'local',
    runtimeOwner: 'canonical-store',
    storeIndexVisibility: 'visible',
    detailRoute: '/store/template/modern-catalog',
    previewRoute: '/store/template/modern-catalog/preview',
    customizeRoute: '/store/customize/modern-catalog',
    pricePresentation: V1_PRICE_PRESENTATION,
    baseRecommendation: 'website',
    upgradeRecommendation: 'website-portal',
    featured: false,
    sortOrder: 2,
    runtimeKey: 'modern-catalog',
  },
  'trust-profile': {
    slug: 'trust-profile',
    name: 'Trust Profile',
    shortName: 'Trust',
    category: 'jasa-profesional',
    businessTypes: ['consultant', 'agency', 'professional-practice', 'creative-studio'],
    capabilities: [
      'public.business-profile',
      'public.catalog',
      'public.item-detail',
      'public.process',
      'public.lead-form',
      'public.consultation',
      'public.whatsapp-contact',
    ],
    optionalCapabilities: [
      'ops.inquiry-follow-up',
      'ops.customer-records',
      'ops.internal-users',
      'ops.admin-dashboard',
      'account.member-login',
    ],
    shortDescription: 'Untuk jasa profesional yang mendapatkan percakapan dari profil, proses, dan hasil kerja yang jelas.',
    positioning: 'Contoh tampilan yang membangun kepercayaan sebelum calon pelanggan memulai percakapan.',
    customerCan: [
      'public.business-profile',
      'public.catalog',
      'public.item-detail',
      'public.lead-form',
      'public.consultation',
      'public.whatsapp-contact',
    ],
    includedFeatures: [
      'Profil bisnis dan layanan',
      'Penjelasan proses dan cara kerja',
      'Form kontak awal untuk tindak lanjut',
      'Jalur konsultasi melalui WhatsApp',
    ],
    optionalFeatures: [
      'Tindak lanjuti pertanyaan dan data pelanggan',
      'Halaman kerja internal untuk kebutuhan operasional ringan',
      'Akses member bila alur layanan membutuhkannya, tanpa mengklaim CRM penuh',
    ],
    previewStatus: 'preview',
    runtimeStatus: 'local',
    runtimeOwner: 'canonical-store',
    storeIndexVisibility: 'visible',
    detailRoute: '/store/template/trust-profile',
    previewRoute: '/store/template/trust-profile/preview',
    customizeRoute: '/store/customize/trust-profile',
    pricePresentation: V1_PRICE_PRESENTATION,
    baseRecommendation: 'website',
    upgradeRecommendation: 'website-portal',
    featured: false,
    sortOrder: 3,
    runtimeKey: 'trust-profile',
  },
  'care-booking': {
    slug: 'care-booking',
    name: 'Care Booking',
    shortName: 'Care',
    category: 'klinik-wellness',
    businessTypes: ['clinic', 'practitioner', 'wellness-practice'],
    capabilities: [
      'public.catalog',
      'public.item-detail',
      'public.schedule-info',
      'public.location',
      'public.booking-request',
      'public.whatsapp-contact',
      'public.process',
    ],
    optionalCapabilities: [
      'ops.content-management',
      'ops.booking-management',
      'ops.availability',
      'ops.customer-records',
      'ops.practitioner-management',
      'ops.reminders',
      'ops.internal-users',
      'ops.admin-dashboard',
      'account.customer-login',
      'account.booking-history',
    ],
    shortDescription: 'Untuk klinik, praktisi, dan layanan wellness yang membutuhkan jalur permintaan jadwal yang jelas.',
    positioning: 'Contoh tampilan yang membantu bisnis layanan menjelaskan kebutuhan sebelum pelanggan datang.',
    customerCan: [
      'public.catalog',
      'public.item-detail',
      'public.schedule-info',
      'public.location',
      'public.booking-request',
      'public.whatsapp-contact',
    ],
    includedFeatures: [
      'Daftar layanan dan detail perawatan',
      'Informasi praktisi dan jadwal',
      'Permintaan appointment sebelum konfirmasi',
      'Lokasi dan informasi kunjungan',
    ],
    optionalFeatures: [
      'Kelola booking, ketersediaan, praktisi, dan data pelanggan',
      'Pengingat dan halaman kerja untuk tim',
      'Login pelanggan dan riwayat booking bila dibutuhkan',
    ],
    previewStatus: 'preview',
    runtimeStatus: 'local',
    runtimeOwner: 'canonical-store',
    storeIndexVisibility: 'visible',
    detailRoute: '/store/template/care-booking',
    previewRoute: '/store/template/care-booking/preview',
    customizeRoute: '/store/customize/care-booking',
    pricePresentation: V1_PRICE_PRESENTATION,
    baseRecommendation: 'website',
    upgradeRecommendation: 'website-portal',
    featured: false,
    sortOrder: 4,
    runtimeKey: 'care-booking',
  },
  'course-enrollment': {
    slug: 'course-enrollment',
    name: 'Course Enrollment',
    shortName: 'Course',
    category: 'edukasi',
    businessTypes: ['course-provider', 'tutoring', 'training-center', 'academy'],
    capabilities: [
      'public.catalog',
      'public.item-detail',
      'public.schedule-info',
      'public.enrollment-request',
      'public.process',
      'public.whatsapp-contact',
    ],
    optionalCapabilities: [
      'ops.content-management',
      'ops.enrollment-management',
      'ops.class-management',
      'ops.customer-records',
      'ops.reminders',
      'ops.payment-management',
      'ops.internal-users',
      'ops.admin-dashboard',
      'account.student-login',
      'account.member-login',
      'account.learning-materials',
      'account.attendance',
      'account.membership',
    ],
    shortDescription: 'Untuk kursus, bimbingan belajar, pelatihan, dan akademi yang perlu menjelaskan program sebelum pendaftaran.',
    positioning: 'Contoh tampilan program yang membantu bisnis edukasi menjelaskan langkah berikutnya sebelum pendaftaran.',
    customerCan: [
      'public.catalog',
      'public.item-detail',
      'public.schedule-info',
      'public.enrollment-request',
      'public.whatsapp-contact',
    ],
    includedFeatures: [
      'Daftar program dan detail kelas',
      'Informasi jadwal dan alur belajar',
      'Permintaan minat pendaftaran',
      'Jalur konsultasi sebelum pendaftaran',
    ],
    optionalFeatures: [
      'Kelola pendaftaran, kelas, jadwal, dan peserta',
      'Pembayaran dan pengingat sesuai kebutuhan operasional',
      'Login siswa/member, materi, kehadiran, dan keanggotaan',
    ],
    previewStatus: 'preview',
    runtimeStatus: 'local',
    runtimeOwner: 'canonical-store',
    storeIndexVisibility: 'visible',
    detailRoute: '/store/template/course-enrollment',
    previewRoute: '/store/template/course-enrollment/preview',
    customizeRoute: '/store/customize/course-enrollment',
    pricePresentation: V1_PRICE_PRESENTATION,
    baseRecommendation: 'website',
    upgradeRecommendation: 'bundle',
    featured: false,
    sortOrder: 5,
    runtimeKey: 'course-enrollment',
  },
  'easy-booking': {
    slug: 'easy-booking',
    name: 'Easy Booking',
    shortName: 'Easy',
    category: 'rental',
    businessTypes: ['car-rental', 'motorcycle-rental', 'equipment-rental', 'property-rental'],
    capabilities: [
      'public.catalog',
      'public.item-detail',
      'public.search-filter',
      'public.price-display',
      'public.location',
      'public.booking-request',
      'public.whatsapp-contact',
      'public.process',
    ],
    optionalCapabilities: [
      'ops.content-management',
      'ops.booking-management',
      'ops.availability',
      'ops.inventory',
      'ops.customer-records',
      'ops.payment-management',
      'ops.internal-users',
      'ops.admin-dashboard',
      'account.customer-login',
      'account.booking-history',
      'account.order-tracking',
    ],
    shortDescription: 'Untuk bisnis rental yang perlu menampilkan unit, spesifikasi, dan jalur permintaan booking yang jelas.',
    positioning: 'Contoh tampilan rental yang membantu pengunjung membandingkan unit sebelum meminta tanggal.',
    customerCan: [
      'public.catalog',
      'public.item-detail',
      'public.search-filter',
      'public.price-display',
      'public.location',
      'public.booking-request',
      'public.whatsapp-contact',
    ],
    includedFeatures: [
      'Katalog unit dan kategori rental',
      'Spesifikasi dan contoh harga unit',
      'Pencarian dan perbandingan pilihan',
      'Permintaan booking untuk dikonfirmasi admin',
    ],
    optionalFeatures: [
      'Kelola unit, ketersediaan, booking, inventaris, dan pelanggan',
      'Pembayaran dan status transaksi sesuai kebutuhan',
      'Login pelanggan, riwayat booking, dan lacak order bila dibutuhkan',
    ],
    previewStatus: 'preview',
    runtimeStatus: 'local',
    runtimeOwner: 'canonical-store',
    storeIndexVisibility: 'visible',
    detailRoute: '/store/template/easy-booking',
    previewRoute: '/store/template/easy-booking/preview',
    customizeRoute: '/store/customize/easy-booking',
    pricePresentation: V1_PRICE_PRESENTATION,
    baseRecommendation: 'website',
    upgradeRecommendation: 'website-portal',
    featured: false,
    sortOrder: 6,
    runtimeKey: 'easy-booking',
  },
} as const satisfies Record<TemplateSlug, StoreTemplate>

export const STORE_TEMPLATE_REGISTRY: readonly StoreTemplate[] = TEMPLATE_SLUGS.map(
  (slug) => STORE_TEMPLATES_BY_SLUG[slug],
)

export function isTemplateSlug(value: string): value is TemplateSlug {
  return (TEMPLATE_SLUGS as readonly string[]).includes(value)
}

export function getStoreTemplateBySlug(slug: string): StoreTemplate | undefined {
  return isTemplateSlug(slug) ? STORE_TEMPLATES_BY_SLUG[slug] : undefined
}

export function getStoreTemplate(slug: TemplateSlug): StoreTemplate {
  return STORE_TEMPLATES_BY_SLUG[slug]
}
