import { V1_PRICE_PRESENTATION } from './capabilities'
import type { StoreCategoryId, StoreTemplate, TemplateSlug } from './types'
import { TEMPLATE_SLUGS } from './types'

export const STORE_CATEGORY_LABELS = {
  kuliner: 'Kuliner',
  retail: 'Retail',
  'jasa-profesional': 'Jasa Profesional',
  'klinik-wellness': 'Klinik & Wellness',
  edukasi: 'Edukasi',
  rental: 'Rental',
} as const satisfies Record<StoreCategoryId, string>

export const STORE_TEMPLATES_BY_SLUG = {
  'warm-commerce': {
    slug: 'warm-commerce',
    name: 'Warm Commerce',
    shortName: 'Warm',
    category: 'kuliner',
    businessTypes: ['restaurant', 'cafe', 'bakery', 'food-service'],
    capabilities: [
      'public.catalog',
      'public.item-detail',
      'public.price-display',
      'public.whatsapp-contact',
      'public.order-request',
      'public.location',
      'public.process',
    ],
    optionalCapabilities: [
      'ops.content-management',
      'ops.order-management',
      'ops.inquiry-follow-up',
      'ops.inventory',
      'ops.customer-records',
      'ops.internal-users',
      'ops.admin-dashboard',
      'account.customer-login',
      'account.order-tracking',
    ],
    shortDescription: 'For food businesses that need a clear menu, price context, and a direct order request path.',
    positioning: 'A menu-led direction that helps food businesses turn browsing into a clear conversation about an order.',
    customerCan: [
      'public.catalog',
      'public.item-detail',
      'public.price-display',
      'public.whatsapp-contact',
      'public.order-request',
    ],
    includedFeatures: [
      'Menu dan katalog makanan',
      'Detail produk dan contoh harga',
      'Permintaan order langsung melalui WhatsApp',
      'Lokasi dan informasi kunjungan',
    ],
    optionalFeatures: [
      'Kelola katalog, order, stok, dan data pelanggan',
      'Dashboard operasional dengan akses tim internal',
      'Login pelanggan dan pelacakan order sesuai scope',
    ],
    previewStatus: 'coming-soon',
    runtimeStatus: 'pending-migration',
    runtimeOwner: 'public-webzoka',
    storeIndexVisibility: 'hidden-until-runtime',
    detailRoute: '/store/template/warm-commerce',
    previewRoute: '/store/template/warm-commerce/preview',
    pricePresentation: V1_PRICE_PRESENTATION,
    baseRecommendation: 'website',
    upgradeRecommendation: 'website-portal',
    featured: true,
    sortOrder: 1,
    runtimeKey: 'warm-commerce',
  },
  'modern-catalog': {
    slug: 'modern-catalog',
    name: 'Modern Catalog',
    shortName: 'Modern',
    category: 'retail',
    businessTypes: ['retail-brand', 'fashion-brand', 'home-living', 'lifestyle-brand'],
    capabilities: [
      'public.catalog',
      'public.item-detail',
      'public.search-filter',
      'public.price-display',
      'public.inquiry',
      'public.whatsapp-contact',
      'public.process',
    ],
    optionalCapabilities: [
      'ops.content-management',
      'ops.order-management',
      'ops.inventory',
      'ops.customer-records',
      'ops.internal-users',
      'ops.admin-dashboard',
      'account.customer-login',
      'account.order-tracking',
    ],
    shortDescription: 'For considered objects, tight collections, and enquiries that need context.',
    positioning: 'A product-led direction for curated collections where context matters before an inquiry.',
    customerCan: [
      'public.catalog',
      'public.item-detail',
      'public.search-filter',
      'public.price-display',
      'public.inquiry',
      'public.whatsapp-contact',
    ],
    includedFeatures: [
      'Katalog produk dan koleksi',
      'Pencarian dan filter pilihan',
      'Detail produk, varian, dan contoh harga',
      'Jalur inquiry untuk pertanyaan lanjutan',
    ],
    optionalFeatures: [
      'Kelola katalog, order, stok, dan data pelanggan',
      'Dashboard operasional dengan akses tim internal',
      'Login pelanggan dan pelacakan order sesuai scope',
    ],
    previewStatus: 'preview',
    runtimeStatus: 'local',
    runtimeOwner: 'canonical-store',
    storeIndexVisibility: 'visible',
    detailRoute: '/store/template/modern-catalog',
    previewRoute: '/store/template/modern-catalog/preview',
    pricePresentation: V1_PRICE_PRESENTATION,
    baseRecommendation: 'website',
    upgradeRecommendation: 'website-portal',
    featured: false,
    sortOrder: 2,
    runtimeKey: 'modern-catalog',
  },
  'trust-profile': {
    slug: 'trust-profile',
    name: 'Trust Profile',
    shortName: 'Trust',
    category: 'jasa-profesional',
    businessTypes: ['consultant', 'agency', 'professional-practice', 'creative-studio'],
    capabilities: [
      'public.business-profile',
      'public.catalog',
      'public.item-detail',
      'public.process',
      'public.lead-form',
      'public.consultation',
      'public.whatsapp-contact',
    ],
    optionalCapabilities: [
      'ops.inquiry-follow-up',
      'ops.customer-records',
      'ops.internal-users',
      'ops.admin-dashboard',
      'account.member-login',
    ],
    shortDescription: 'For professional services that earn a conversation through clarity, process, and considered work.',
    positioning: 'A credibility-led direction for professional services that need clarity before a conversation.',
    customerCan: [
      'public.business-profile',
      'public.catalog',
      'public.item-detail',
      'public.lead-form',
      'public.consultation',
      'public.whatsapp-contact',
    ],
    includedFeatures: [
      'Profil bisnis dan layanan',
      'Penjelasan proses dan cara kerja',
      'Form kontak awal untuk tindak lanjut',
      'Jalur konsultasi melalui WhatsApp',
    ],
    optionalFeatures: [
      'Tindak lanjut inquiry dan data pelanggan',
      'Dashboard internal untuk kebutuhan operasional ringan',
      'Akses member bila alur layanan membutuhkannya, tanpa mengklaim full CRM',
    ],
    previewStatus: 'preview',
    runtimeStatus: 'local',
    runtimeOwner: 'canonical-store',
    storeIndexVisibility: 'visible',
    detailRoute: '/store/template/trust-profile',
    previewRoute: '/store/template/trust-profile/preview',
    pricePresentation: V1_PRICE_PRESENTATION,
    baseRecommendation: 'website',
    upgradeRecommendation: 'website-portal',
    featured: false,
    sortOrder: 3,
    runtimeKey: 'trust-profile',
  },
  'care-booking': {
    slug: 'care-booking',
    name: 'Care Booking',
    shortName: 'Care',
    category: 'klinik-wellness',
    businessTypes: ['clinic', 'practitioner', 'wellness-practice'],
    capabilities: [
      'public.catalog',
      'public.item-detail',
      'public.schedule-info',
      'public.location',
      'public.booking-request',
      'public.whatsapp-contact',
      'public.process',
    ],
    optionalCapabilities: [
      'ops.content-management',
      'ops.booking-management',
      'ops.availability',
      'ops.customer-records',
      'ops.practitioner-management',
      'ops.reminders',
      'ops.internal-users',
      'ops.admin-dashboard',
      'account.customer-login',
      'account.booking-history',
    ],
    shortDescription: 'For clinics, practitioners, wellness, and care services that need a clear appointment request path.',
    positioning: 'A calm appointment-request direction that gives care businesses clarity before arrival.',
    customerCan: [
      'public.catalog',
      'public.item-detail',
      'public.schedule-info',
      'public.location',
      'public.booking-request',
      'public.whatsapp-contact',
    ],
    includedFeatures: [
      'Daftar layanan dan detail perawatan',
      'Informasi praktisi dan jadwal',
      'Permintaan appointment sebelum konfirmasi',
      'Lokasi dan informasi kunjungan',
    ],
    optionalFeatures: [
      'Kelola booking, ketersediaan, praktisi, dan data pelanggan',
      'Pengingat dan dashboard operasional dengan akses tim',
      'Login pelanggan dan riwayat booking bila diminta',
    ],
    previewStatus: 'preview',
    runtimeStatus: 'local',
    runtimeOwner: 'canonical-store',
    storeIndexVisibility: 'visible',
    detailRoute: '/store/template/care-booking',
    previewRoute: '/store/template/care-booking/preview',
    pricePresentation: V1_PRICE_PRESENTATION,
    baseRecommendation: 'website',
    upgradeRecommendation: 'website-portal',
    featured: false,
    sortOrder: 4,
    runtimeKey: 'care-booking',
  },
  'course-enrollment': {
    slug: 'course-enrollment',
    name: 'Course Enrollment',
    shortName: 'Course',
    category: 'edukasi',
    businessTypes: ['course-provider', 'tutoring', 'training-center', 'academy'],
    capabilities: [
      'public.catalog',
      'public.item-detail',
      'public.schedule-info',
      'public.enrollment-request',
      'public.process',
      'public.whatsapp-contact',
    ],
    optionalCapabilities: [
      'ops.content-management',
      'ops.enrollment-management',
      'ops.class-management',
      'ops.customer-records',
      'ops.reminders',
      'ops.payment-management',
      'ops.internal-users',
      'ops.admin-dashboard',
      'account.student-login',
      'account.member-login',
      'account.learning-materials',
      'account.attendance',
      'account.membership',
    ],
    shortDescription: 'For courses, tutoring, training, and academies that need program clarity before enrollment.',
    positioning: 'A structured program-discovery direction that helps education businesses explain the next step before enrollment.',
    customerCan: [
      'public.catalog',
      'public.item-detail',
      'public.schedule-info',
      'public.enrollment-request',
      'public.whatsapp-contact',
    ],
    includedFeatures: [
      'Daftar program dan detail kelas',
      'Informasi jadwal dan alur belajar',
      'Permintaan minat pendaftaran',
      'Jalur konsultasi sebelum enrollment',
    ],
    optionalFeatures: [
      'Kelola pendaftaran, kelas, jadwal, dan peserta',
      'Pembayaran dan pengingat sesuai scope operasional',
      'Student/member login, materi, kehadiran, dan membership',
    ],
    previewStatus: 'preview',
    runtimeStatus: 'local',
    runtimeOwner: 'canonical-store',
    storeIndexVisibility: 'visible',
    detailRoute: '/store/template/course-enrollment',
    previewRoute: '/store/template/course-enrollment/preview',
    pricePresentation: V1_PRICE_PRESENTATION,
    baseRecommendation: 'website',
    upgradeRecommendation: 'bundle',
    featured: false,
    sortOrder: 5,
    runtimeKey: 'course-enrollment',
  },
  'easy-booking': {
    slug: 'easy-booking',
    name: 'Easy Booking',
    shortName: 'Easy',
    category: 'rental',
    businessTypes: ['car-rental', 'motorcycle-rental', 'equipment-rental', 'property-rental'],
    capabilities: [
      'public.catalog',
      'public.item-detail',
      'public.search-filter',
      'public.price-display',
      'public.location',
      'public.booking-request',
      'public.whatsapp-contact',
      'public.process',
    ],
    optionalCapabilities: [
      'ops.content-management',
      'ops.booking-management',
      'ops.availability',
      'ops.inventory',
      'ops.customer-records',
      'ops.payment-management',
      'ops.internal-users',
      'ops.admin-dashboard',
      'account.customer-login',
      'account.booking-history',
      'account.order-tracking',
    ],
    shortDescription: 'For rental businesses that need clear unit discovery, useful specs, and an honest booking inquiry path.',
    positioning: 'A rental discovery direction that helps visitors compare units before requesting dates.',
    customerCan: [
      'public.catalog',
      'public.item-detail',
      'public.search-filter',
      'public.price-display',
      'public.location',
      'public.booking-request',
      'public.whatsapp-contact',
    ],
    includedFeatures: [
      'Katalog unit dan kategori rental',
      'Spesifikasi dan contoh harga unit',
      'Pencarian dan perbandingan pilihan',
      'Permintaan booking untuk dikonfirmasi admin',
    ],
    optionalFeatures: [
      'Kelola unit, ketersediaan, booking, inventaris, dan pelanggan',
      'Pembayaran dan status transaksi sesuai scope',
      'Login pelanggan, riwayat booking, dan pelacakan order bila diminta',
    ],
    previewStatus: 'preview',
    runtimeStatus: 'local',
    runtimeOwner: 'canonical-store',
    storeIndexVisibility: 'visible',
    detailRoute: '/store/template/easy-booking',
    previewRoute: '/store/template/easy-booking/preview',
    pricePresentation: V1_PRICE_PRESENTATION,
    baseRecommendation: 'website',
    upgradeRecommendation: 'website-portal',
    featured: false,
    sortOrder: 6,
    runtimeKey: 'easy-booking',
  },
} as const satisfies Record<TemplateSlug, StoreTemplate>

export const STORE_TEMPLATE_REGISTRY: readonly StoreTemplate[] = TEMPLATE_SLUGS.map(
  (slug) => STORE_TEMPLATES_BY_SLUG[slug],
)

export function getStoreTemplate(slug: TemplateSlug): StoreTemplate {
  return STORE_TEMPLATES_BY_SLUG[slug]
}
